name: Create Release

on:
  push:
    tags:
      - 'v*.*.*' # Matches version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Create archive
        run: zip -r release-v${GITHUB_REF##*/}.zip ./

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-v${GITHUB_REF##*/}.zip
          asset_name: release-v${GITHUB_REF##*/}.zip
          asset_content_type: application/zip
